`tf.data.Dataset`으로 pandas 데이터를 load하는 방법

## Pandas로 data를 read하기

In [1]:
import pandas as pd
import tensorflow as tf

In [2]:
csv_file = tf.keras.utils.get_file('heart.csv', 'https://storage.googleapis.com/applied-dl/heart.csv')

16384/13273 [=====================================] - 0s 1us/step


In [3]:
df = pd.read_csv(csv_file)

In [4]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca        thal  target  
0   0       fixed       0  
1   3      normal       1  
2   2  reversible       0  
3   0      normal       0  
4   0      normal       0

In [5]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal         object
target        int64
dtype: object

`thal` 항목의 `object`를 int형으로 변환

In [14]:
df['thal'] = pd.Categorical(df['thal'])  # Category 형식으로 변환
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca thal  target  
0   0    2       0  
1   3    3       1  
2   2    4       0  
3   0    3       0  
4   0    3       0

In [11]:
df.dtypes

age            int64
sex            int64
cp             int64
trestbps       int64
chol           int64
fbs            int64
restecg        int64
thalach        int64
exang          int64
oldpeak      float64
slope          int64
ca             int64
thal        category
target         int64
dtype: object

In [15]:
df['thal'] = df.thal.cat.codes # Category형식을 int형식으로 변환

In [16]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca  thal  target  
0   0     2       0  
1   3     3       1  
2   2     4       0  
3   0     3       0  
4   0     3       0

## data를 `tf.data.Dataset`으로 load
 `tf.data.Dataset.from_tensor_slices`을 이용해 pandas dataframe을 사용할 수 있다.

In [17]:
target = df.pop('target')  # labels

In [18]:
dataset = tf.data.Dataset.from_tensor_slices((df.values, target.values))  # data, label

In [19]:
for feat, targ in dataset.take(5):
    print ('Features: {}, Target: {}'.format(feat, targ))

Features: [ 63.    1.    1.  145.  233.    1.    2.  150.    0.    2.3   3.    0.
   2. ], Target: 0
Features: [ 67.    1.    4.  160.  286.    0.    2.  108.    1.    1.5   2.    3.
   3. ], Target: 1
Features: [ 67.    1.    4.  120.  229.    0.    2.  129.    1.    2.6   2.    2.
   4. ], Target: 0
Features: [ 37.    1.    3.  130.  250.    0.    0.  187.    0.    3.5   3.    0.
   3. ], Target: 0
Features: [ 41.    0.    2.  130.  204.    0.    2.  172.    0.    1.4   1.    0.
   3. ], Target: 0


In [20]:
tf.constant(df['thal'])

<tf.Tensor: id=21, shape=(303,), dtype=int32, numpy=
array([2, 3, 4, 3, 3, 3, 3, 3, 4, 4, 2, 3, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3,
       3, 4, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 4, 2, 4, 3, 4, 3, 4, 4,
       2, 3, 3, 4, 3, 3, 4, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 4,
       4, 2, 3, 3, 4, 3, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 3, 3, 4, 4, 4,
       3, 3, 4, 3, 4, 4, 3, 4, 3, 3, 3, 4, 3, 4, 4, 3, 3, 4, 4, 4, 4, 4,
       3, 3, 3, 3, 4, 3, 4, 3, 4, 4, 3, 3, 2, 4, 4, 2, 3, 3, 4, 4, 3, 4,
       3, 3, 4, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
       4, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 3, 2,
       4, 4, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 2, 2, 4, 3, 4, 2, 4, 3,
       3, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 2, 2, 4, 3, 4, 3, 2, 4, 3, 3, 2,
       4, 4, 4, 4, 3, 0, 3, 3, 3, 3, 1, 4, 3, 3, 3, 4, 3, 4, 3, 3, 3, 4,
       3, 3, 4, 4, 4, 4, 3, 3, 4, 3, 4, 3, 4, 4, 3, 4, 4, 3, 4, 4, 3, 3

Shuffle and batch the dataset.

In [21]:
train_dataset = dataset.shuffle(len(df)).batch(1)

## 모델 빌드 및 학습

In [22]:
def get_compiled_model():
  model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(1)
  ])

  model.compile(optimizer='adam',
                loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                metrics=['accuracy'])
  return model

In [23]:
model = get_compiled_model()
model.fit(train_dataset, epochs=15)


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

Epoch 1/15
303/303 [==============================] - 2s 6ms/step - loss: 12.2269 - accuracy: 0.6931
Epoch 2/15
303/303 [==============================] - 1s 3ms/step - loss: 0.6619 - accuracy: 0.7294
Epoch 3/15
303/303 [==============================] - 1s 2ms/step - loss: 0.6071 - accuracy: 0.7327
Epoch 4/15
303/303 [==============================] - 1s 2ms/step - loss: 0.6262 - accuracy: 0.7096
Epoch 5/15
303/303 [==============================] - 1s 3ms/step - loss: 0.5877 - accuracy: 0.7426
Epoch 6

## Functional api 모델 형식

In [24]:
inputs = {key: tf.keras.layers.Input(shape=(), name=key) for key in df.keys()}

In [25]:
inputs

{'age': <tf.Tensor 'age:0' shape=(None,) dtype=float32>,
 'sex': <tf.Tensor 'sex:0' shape=(None,) dtype=float32>,
 'cp': <tf.Tensor 'cp:0' shape=(None,) dtype=float32>,
 'trestbps': <tf.Tensor 'trestbps:0' shape=(None,) dtype=float32>,
 'chol': <tf.Tensor 'chol:0' shape=(None,) dtype=float32>,
 'fbs': <tf.Tensor 'fbs:0' shape=(None,) dtype=float32>,
 'restecg': <tf.Tensor 'restecg:0' shape=(None,) dtype=float32>,
 'thalach': <tf.Tensor 'thalach:0' shape=(None,) dtype=float32>,
 'exang': <tf.Tensor 'exang:0' shape=(None,) dtype=float32>,
 'oldpeak': <tf.Tensor 'oldpeak:0' shape=(None,) dtype=float32>,
 'slope': <tf.Tensor 'slope:0' shape=(None,) dtype=float32>,
 'ca': <tf.Tensor 'ca:0' shape=(None,) dtype=float32>,
 'thal': <tf.Tensor 'thal:0' shape=(None,) dtype=float32>}

In [26]:
x = tf.stack(list(inputs.values()), axis=-1)

In [27]:
x

<tf.Tensor 'stack:0' shape=(None, 13) dtype=float32>

In [28]:
x = tf.keras.layers.Dense(10, activation='relu')(x)
output = tf.keras.layers.Dense(1)(x)

model_func = tf.keras.Model(inputs=inputs, outputs=output)

model_func.compile(optimizer='adam',
                   loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                   metrics=['accuracy'])

In [29]:
dict_slices = tf.data.Dataset.from_tensor_slices((df.to_dict('list'), target.values)).batch(16)

In [30]:
dict_slices

<BatchDataset shapes: ({age: (None,), sex: (None,), cp: (None,), trestbps: (None,), chol: (None,), fbs: (None,), restecg: (None,), thalach: (None,), exang: (None,), oldpeak: (None,), slope: (None,), ca: (None,), thal: (None,)}, (None,)), types: ({age: tf.int32, sex: tf.int32, cp: tf.int32, trestbps: tf.int32, chol: tf.int32, fbs: tf.int32, restecg: tf.int32, thalach: tf.int32, exang: tf.int32, oldpeak: tf.float32, slope: tf.int32, ca: tf.int32, thal: tf.int32}, tf.int64)>

In [31]:
dict_slices.take(1)

<TakeDataset shapes: ({age: (None,), sex: (None,), cp: (None,), trestbps: (None,), chol: (None,), fbs: (None,), restecg: (None,), thalach: (None,), exang: (None,), oldpeak: (None,), slope: (None,), ca: (None,), thal: (None,)}, (None,)), types: ({age: tf.int32, sex: tf.int32, cp: tf.int32, trestbps: tf.int32, chol: tf.int32, fbs: tf.int32, restecg: tf.int32, thalach: tf.int32, exang: tf.int32, oldpeak: tf.float32, slope: tf.int32, ca: tf.int32, thal: tf.int32}, tf.int64)>

In [32]:
for dict_slice in dict_slices.take(1):
    print(dict_slice)

({'age': <tf.Tensor: id=14748, shape=(16,), dtype=int32, numpy=array([63, 67, 67, 37, 41, 56, 62, 57, 63, 53, 57, 56, 56, 44, 52, 57])>, 'sex': <tf.Tensor: id=14756, shape=(16,), dtype=int32, numpy=array([1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1])>, 'cp': <tf.Tensor: id=14751, shape=(16,), dtype=int32, numpy=array([1, 4, 4, 3, 2, 2, 4, 4, 4, 4, 4, 2, 3, 2, 3, 3])>, 'trestbps': <tf.Tensor: id=14760, shape=(16,), dtype=int32, numpy=
array([145, 160, 120, 130, 130, 120, 140, 120, 130, 140, 140, 140, 130,
       120, 172, 150])>, 'chol': <tf.Tensor: id=14750, shape=(16,), dtype=int32, numpy=
array([233, 286, 229, 250, 204, 236, 268, 354, 254, 203, 192, 294, 256,
       263, 199, 168])>, 'fbs': <tf.Tensor: id=14753, shape=(16,), dtype=int32, numpy=array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0])>, 'restecg': <tf.Tensor: id=14755, shape=(16,), dtype=int32, numpy=array([2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0, 0])>, 'thalach': <tf.Tensor: id=14759, shape=(16,), dtype=int32, n

In [33]:
model_func.fit(dict_slices, epochs=15)

Epoch 1/15
19/19 [==============================] - 0s 24ms/step - loss: 45.2960 - accuracy: 0.7261
Epoch 2/15
19/19 [==============================] - 0s 6ms/step - loss: 35.0033 - accuracy: 0.7261
Epoch 3/15
19/19 [==============================] - 0s 6ms/step - loss: 27.5135 - accuracy: 0.7261
Epoch 4/15
19/19 [==============================] - 0s 6ms/step - loss: 20.6102 - accuracy: 0.7261
Epoch 5/15
19/19 [==============================] - 0s 6ms/step - loss: 13.9186 - accuracy: 0.7261
Epoch 6/15
19/19 [==============================] - 0s 6ms/step - loss: 7.5156 - accuracy: 0.6964
Epoch 7/15
19/19 [==============================] - 0s 6ms/step - loss: 4.8829 - accuracy: 0.4785
Epoch 8/15
19/19 [==============================] - 0s 6ms/step - loss: 3.9804 - accuracy: 0.5677
Epoch 9/15
19/19 [==============================] - 0s 6ms/step - loss: 3.4656 - accuracy: 0.5842
Epoch 10/15
19/19 [==============================] - 0s 6ms/step - loss: 3.0164 - accuracy: 0.5875
Epoch 11/15
1